### ISSUE TITLE
Pull Requests are listed in JIRA as status = "Declined" instead of "Closed"

### ISSUE THREAD

**Issue by Drewpeifer** [atlassian/github-for-jira#372] opened 2020-06-23 22:42 UTC
I am not sure if this is intended, but our Pull Requests are showing up as "Declined" after the PR has been approved. After approving the PR, we then merge the branch, the branch is deleted, the PR is closed, and that's when we see the status in JIRA change to "Declined".

![PR-appears-declined](https://user-images.githubusercontent.com/30933/85472151-795f8a80-b57f-11ea-8c55-b6e4fabdc0a8.png)

If this is intended, I would request to change the language used for that status **(within JIRA)** to be "Closed", since "Declined" is a different state than "Closed" (and that's how github.com indicates the status, in the final state):
![git-closed-PR-badge](https://user-images.githubusercontent.com/30933/85472643-1de1cc80-b580-11ea-85d0-941fe7a9a523.png)

If this is related to the branch being deleted, it would also make sense for the PR status to be deleted I guess, but I think **discerning between Closed and Declined** is the more important factor in our use case.

If this is unintended, I can provide more details as needed on our (cloud) installation, or our specific workflow within JIRA or git. I can say with confidence though that our workflow and setup are both fairly basic (we just created this instance, we have no automation events triggered via git, etc).

**Comment by Drewpeifer** [comment] 2020-06-24 18:42
I also tested this by opening a PR myself then closing it a moment later, and the status immediately changes to "Declined" in JIRA. So it doesn't seem related to a workflow / process issue, more likely just a clarification needed in the response from git / the plugin's display value in JIRA.

**Comment by corytodd** [comment] 2021-04-30 18:06
We see this as well and causes some confusion. I think its because we use gitflow which marks the PR as closed, not necessarily as merged. The same workflow works fine for our Bitbucket repos.

**Comment by rachellerathbone** [comment] 2021-05-17 23:19
Hi @Drewpeifer. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

I've flagged this with the 'to triage' label so my team can discuss. We'll keep you posted on the status of this.

**Comment by bxk-sonavex** [comment] 2021-05-19 03:21
Experiencing the same issue as well

**Comment by rachellerathbone** [comment] 2021-05-20 00:09
Hi @Drewpeifer and @bxk-sonavex. I've created a ticket in the backlog for my team. We'll update you when we can. Stay tuned 😄

**Comment by joelbarker2011** [comment] 2021-07-14 23:07
Experiencing this issue multiple times now in the last few days. It always worked flawlessly before and we have not changed our process at all. Very annoying since we have certain Jira actions that are supposed to be triggered when a pull request is closed, but these are not firing since Jira thinks the PR was declined instead.

**Comment by mboudreau** [comment] 2021-07-15 02:55
@joelbarker2011 There's only one place where this status is set and it's [here](https://github.com/integrations/jira/blob/58fbd9f8538d21e4e1fdc04c092058bcfdcb515a/lib/transforms/pull-request.js#L13): `if (status === 'closed' && !merged) return 'DECLINED';`

We're basing this functionality on the [Github Event Payload documentation](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request), specifically:

> If the action is closed and the merged key is false, the pull request was closed with unmerged commits. If the action is closed and the merged key is true, the pull request was merged.

I guess the question becomes, does the the PR become closed, but is never merged?
If it does get merged and is closed, we'll need to debug further to see what is happening for it to change the status.  Could this be done because of some jira automation?

**Comment by celinakRS** [comment] 2021-08-09 14:30
In our case I've seen this multiple times when the:
PR was originally declined--> then more work done to address the review --> original review was dismissed --> new review was requested --> PR was approved --> merged --> original branch deleted.

This is VERY misleading in the JIRA ui as it looks like the PR is still open and merge has not taken place.  The status I'm expecting to see in JIRA is Merged. Since it was in fact, merged. :)

**Comment by mboudreau** [comment] 2021-08-10 02:07
Ah right,  yes, that's correct.  I didn't know that we already knew of this issue but with the migration going on, it's gone in the backlog because other things were of higher priority.  

I'll see if we can bring this up and address it in the coming days.

**Comment by usmonster** [comment] 2021-08-11 11:15
> I've also seen this happen when the PR was never originally declined:
> PR created --> PR approved --> merged --> original branch deleted --> approver left a comment

This is the main one that I'm noticing. This is unambiguously wrong behavior and seems like a straightforward fix. If it turns out the team can't address it in the coming days, would a PR be welcome? Thanks!

**Comment by StevenACoffman** [comment] 2021-08-11 17:34
Yes, they've said both that a) PRs are welcome, and b) they cannot address it quickly otherwise

**Comment by mboudreau** [comment] 2021-08-12 01:44
@usmonster PRs are always welcome, however, @atrigueiro did have a look at it and she simply could not reproduce it.  I looked at the logic myself and it seems to make sense as to what it's doing (feel free to look at the code yourself).

What I think might be happening though is a timing issue between what's coming in from github webhook events and what we process and send to Jira.  When you have rules like deleting the PR branch after a merge and closing the PR, I'm wondering if the events that come in might be in the wrong order and since we don't keep 'state' of what's going on, our code can't know in which order to process them or if it needs to discard an event because a newer one supersedes it.

At this current moment, we can't really investigate this at scale because we don't own the app fully (migration set for the 22nd of August) and we can't look at the logs as they're owned by Github until we do the migration.  We will definitely look at this  further once the migration is complete and we have our own logs we can sift through.

**One thing that you can do to help us debug this issue though**, if you could go into the Github configuration in Jira and do a _full_ resync of the organization giving you trouble.  Wait for it to complete (might take a little while) then look to see if the problem is fixed and let us know of the result.  

Thanks!

**Comment by usmonster** [comment] 2021-08-12 14:51
Thanks for the quick and thorough response!

After skimming some code and GitHub API docs and a quick test to confirm my suspicion, it looks like not all event payloads include the `merged` field in the returned `pull_request` object. Notably, it seems to be missing from the [`pull_request_review_comment`](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#webhook-payload-example-34) event (GitHub oversight?), so the [`mapStatus` implementation in /lib/transforms/pull-request.js](https://github.com/atlassian/github-for-jira/blob/58fbd9f8538d21e4e1fdc04c092058bcfdcb515a/lib/transforms/pull-request.js#L5-L17) will return `'DECLINED'` in cases there one makes a comment _on a line of code_ in any closed PR.

I've proposed a fix in #603 based on the slightly different implementation found in [/lib**/sync**/transforms/pull-request.js](https://github.com/atlassian/github-for-jira/blob/master/lib/sync/transforms/pull-request.js#L6-L18) (maybe @tebriel discovered this as well?).

**Comment by atrigueiro** [comment] 2021-08-13 00:18
Hi all,

We're finally able to replicate this issue by adding a single line comment on a closed PR.
Thanks to @usmonster, we now also have a PR for it so we're prioritising this work and hoping to get the fix out by next week.

Stay tuned, I'll keep this issue up to date.

**Closed** 2021-08-13 06:02 UTC
Labels: stay tuned

**Comment by mboudreau** [comment] 2021-08-17 08:05
Hi everyone,

Sorry, this got closed a bit too early because even though we merged in @usmonster PR, we hadn't released it to production as we wanted to test it first.  We did hit some snags trying to release it (unrelated issue with heroku), but I can now safely say that the change is now fixed and in production! :tada: 

For all those that's been affected by this issue and want to fix it for historical tickets and such, just go into the app on the Jira side, and where the "Retry" column is, click the organization's dropdown and select "Full" then click "Submit".

![Screenshot from 2021-08-17 17-59-38](https://user-images.githubusercontent.com/573668/129687545-804158cd-b7f5-4e0c-851e-5670604eac96.png)

This will resync your historical data so that everything is back to normal.  If there's any other issues, please let me know.  Big shoutout to everyone helping us identify this issue and @usmonster showing us how to fix it.  Cheers!

**Comment by celinakRS** [comment] 2021-08-17 17:53
Checked this out today and it resolved the scenario I posted above.  Thank you everyone!!
