### ISSUE TITLE
Add environment mapping to achieve a flawless integration experience 

### ISSUE THREAD

**Issue by szymon-halik** [atlassian/github-for-jira#1026] opened 2022-01-10 15:22 UTC
We've recently enabled the integration to track our development progress in Jira in a better way but apparently there is a couple of missing things in regards to the environment mapping. Currently we are using the User Acceptance Testing environment with abbreviation `UAT` which is not mapped [here](https://github.com/atlassian/github-for-jira/blob/main/src/transforms/deployment.ts#L133). This result in an `Unmapped` value in Deployments and an`Undefined environment` in the issue Releases field.  
![Screenshot 2022-01-10 at 16 11 46](https://user-images.githubusercontent.com/35228022/148789311-5d87d692-605c-43f2-b8ef-ba3d8e10e35e.png)
![Screenshot 2022-01-10 at 16 13 16](https://user-images.githubusercontent.com/35228022/148789565-35c612da-eef7-49a0-83d4-9218fe7b2815.png)

Can you please consider to add this small enhancement into the integration mapping values? What is more, there is another common abbreviation that is often used among the DevOps configs in the technology that I am working with called: `SIT` - which stands for System Integration Testing environment

**Comment by mboudreau** [comment] 2022-01-10 23:00
This is a duplicate of https://github.com/atlassian/github-for-jira/issues/895

We understand that there needs to be a better way to do mappings and we do have it in our backlog.  I'm curious though, in your opinion should SIT and UAT be classified as testing or staging?  In the meantime, I'm happy to add those two to the mappings to fix your issue short term.

**Comment by szymon-halik** [comment] 2022-01-11 10:11
@mboudreau thanks for the quick response! 

I would say that in most cases SIT and UAT are classified as testing environments. I have never seen them set up as staging environments to be honest.

**Comment by cehenriques** [comment] 2022-02-01 11:42
We're also facing the same issue. Given that our project has multiple parallel environments, they are not just named "QA" or "PROD", they also have a suffix with the description of the service. e.g.: QaXXX
This makes all the environments to be unmapped in Jira and have the "Undefined environment" issue described above.
It's not a critical issue, since I can click that link and see the details of the deployment where the name of the environments show correctly. It's just on the quick view of the Jira issue that I cannot immediately see the deployment info and I need to do some extra clicks to get to that information.

**Comment by rachellerathbone** [comment] 2022-02-17 03:43
Hey all. We're currently working on something that will allow you to add additional environment mappings per repo. Stay tuned!

**Comment by joegaudet** [comment] 2022-02-23 02:23
Cannot wait!

**Comment by joegaudet** [comment] 2022-03-18 20:55
@rachellerathbone is there any sort of timeline on this? Just doing some project planning :P

**Comment by joegaudet** [comment] 2022-05-02 20:03
@rachellerathbone curious if there's any update here.

**Comment by joegaudet** [comment] 2022-08-09 22:48
@rachellerathbone just checking in, would love to use some of the DORA insights of Jira, but can't currently with this.

**Comment by rachellerathbone** [comment] 2022-08-25 07:13
Hey @joegaudet. Does this help? https://github.com/atlassian/github-for-jira/issues/1303#issuecomment-1226715001

**Comment by cehenriques** [comment] 2022-08-25 08:05
@rachellerathbone that looks great! I think it will solve our issues. Thank you.

**Comment by rachellerathbone** [comment] 2022-08-25 10:48
Awesome! I'm going to close this issue. Please reach out again if you need help with anything else.

**Closed by rachellerathbone** 2022-08-25 10:48 UTC
Labels: enhancement, stay tuned
