### ISSUE TITLE
Unable to change/remove linked repository in Code tab

### ISSUE THREAD

**Issue by monkishtypist** [atlassian/github-for-jira#766] opened 2021-09-21 20:36 UTC
Issue: I am unable to _change or remove_ which **repository** GitHub for Jira app is connected to.

Steps to reproduce:

1. I set up GitHub connector during project creation wizard (new project)
2. I selected to create a new repository <-- my mistake was here 🤭 
3. A new repo in GitHub was created <-- didn't want this 🙅
4. I already have an existing repository I want to connect the project to
5. I deleted the repository that was created by the app in (3) above
6. I am unable to change which repository this is pointing to
7. I have tried uninstalling the app
8. I have tried removing this from GitHub along with all permissions
9. I have uninstalled/reinstalled every possible number of ways
    * limiting access to only select repository
    * uninstalling/reinstalling completely/from scratch
    * re-syncing FULL
    * you name it!
10. When I go to `Project > Code` I still see the "GitHub Connected" card (goes away if I uninstall, returns when reinstall)
11. Also at `Project > Code` I see the incorrect GitHub repository card (which links to 404 because I deleted repository)

Help! How do I update this app in Jira to reference a _different_ repository?

**Comment by rachellerathbone** [comment] 2021-09-22 01:06
Hey @monkishtypist. So I can assist you would you be able to send me some screenshots or a recording of you going through this flow? It will allow me to help pinpoint anything that may be going wrong. Also, please make sure I can see the url for your Jira instance and can see the names of the repo you have both deleted and are trying to connect to so I can have a look in our logs.

**Comment by monkishtypist** [comment] 2021-09-22 16:49
Thanks @rachellerathbone however much of that content is protected by NDA. But perhaps you can recreate the issues locally. Try this:

1. Connect the app to _any_ GitHub repository (note the repo for later) - in my case I selected to _create a **new** repository_
    * Check the project's Code section and note the GitHub cards there, including the one that links out to your GitHub repo above
2. Now try to change the repository to which the app is pointed...

This is not possible.

Also at this point I realized my mistake, and I _deleted_ the repository that was created by the app. However this has ~little~ **no** effect on the following.

After doing the above, now try this:

1. Disable Code in the project settings
2. Uninstall the app from Jira
3. Remove the app from GitHub
    * Github Organization > Settings > Installed GitHub Apps > Jira > Configure > Danger Zone "Uninstall"
4. Check Jira and the GitHub cards are gone from the Code tab <-- this is expected

I tested steps 1-3 above in every order: 123, 132, 213, 231, 312, 321.

But then do this:

1. Reinstall GitHub for Jira app
2. Connect the app to GitHub accordingly and (important!) give permissions to Selected Repositories _**not** including the one you originally connected to in the very first step above_
3. Check your project's Code section - the cards you noted from above (GitHub connected and Repository link) have returned, even tho we have not given permissions to the connected repository!

Apologies I cannot give screenshots, but this step by step should help anyone replicate this problem.

**Comment by rachellerathbone** [comment] 2021-09-24 02:35
@monkishtypist I understand the reason why you can't share screenshots. That said, keep in mind that without them it may make it a little harder to debug the issue and will probably take a little longer to come to a solution. 

With step 1 `Connect the app to any GitHub repository (note the repo for later) - in my case I selected to create a new repository` I'm not sure what you mean by selecting to 'create a new repository'.

**The flow of installing the app:**

-  Click 'Connect GitHub organization'

![Screen Shot 2021-09-24 at 12 20 14 pm](https://user-images.githubusercontent.com/37155488/134608993-e8940013-54a6-4853-95b2-6490fbf50381.png)

-  Either click 'Connect' if your org has previously gone through the OAuth flow with GH, otherwise, click 'Install Jira on a new site'.

![Screen Shot 2021-09-24 at 12 20 30 pm](https://user-images.githubusercontent.com/37155488/134609041-65f61f3a-822a-4303-9bd0-15e9a75f0cea.png)

- If I click 'Connect' I'm redirected back to the GH config page. For the second option, I am directed to the following screen. Here I can find the org that I wish to connect to and click on it.

![Screen Shot 2021-09-24 at 12 20 56 pm](https://user-images.githubusercontent.com/37155488/134609117-176444c0-09e5-4fa9-80f5-bf92f9fc970b.png)

- Now I have the option to choose 'All repositories' or 'Only select repositories. There is no option to create a new repo. Click 'install'

![Screen Shot 2021-09-24 at 12 21 15 pm](https://user-images.githubusercontent.com/37155488/134609195-40005e3c-a345-4c47-84d8-e0488d001f52.png)

 - Now, back on the Connect a GH org to your Jira site pg, I can click 'Connect' on the org I just added. I will then be redirected to the GH config page where I can see the repo/s syncing.

Please confirm these are the steps you have followed so far and clarify what you mean by 'create a new repository' so I can make sure I am reproducing your steps correctly. Once I have clarification I can continue trying to reproduce further steps.

**Comment by rachellerathbone** [comment] 2021-09-24 02:40
I'm wondering if you have this integration installed or a different one. This is the [github-for-jira](https://rachellerathbone.atlassian.net/plugins/servlet/ac/com.atlassian.jira.emcee/enduser-discover?project.key=TEST&project.id=10000#!/discover/app/com.github.integration.production) integration that is owned by Atlassian (this codebase).

**Comment by monkishtypist** [comment] 2021-09-24 15:58
Yes @rachellerathbone that is roughly the steps I went through. And yes, I am using this very integration `github-for-jira`.

I have obfuscated some screenshots below.

1. The first is showing the app we are using, this one.
2. The second shows I have connected to an example repository within my organization (not ALL repos)
3. And the third shows the cards on my projects CODE page:
    a. Bitbucket - not using
    b. GitHub - _correct_  repo
    c. GitHub - _incorrect_ repo

How do I remove/change the third card seen in screenshot (3)? That "WRONG REPOSITORY" has been deleted, does not exist. The card links to a 404 page. When I uninstall the app, cards (b) and (c) go away. When I reinstall the app cards (b) and (c) return, regardless which repositories I select for app permissions seen in screenshot (2).

(1)
<img width="740" alt="Screen Shot 2021-09-24 at 8 44 13 AM" src="https://user-images.githubusercontent.com/7469173/134703460-809a113b-a52d-4aec-9c40-9a4f2d4a6272.png">

(2)
<img width="515" alt="Screen Shot 2021-09-24 at 8 47 09 AM" src="https://user-images.githubusercontent.com/7469173/134703853-34266d52-948b-402f-a40e-0ecb3cc78e6f.png">

(3)
<img width="845" alt="Screen Shot 2021-09-24 at 8 49 05 AM" src="https://user-images.githubusercontent.com/7469173/134704142-d48737e9-35bd-4db5-9d8c-cb4ddb9ba5bf.png">

**Comment by rachellerathbone** [comment] 2021-09-27 06:00
Hey @monkishtypist. Thanks for providing all of the above. I'm still not clear on where you were in the app when you said `in my case I selected to create a new repository` so I have not been able to reproduce your steps as of yet. As you can see in the screenshots I sent, there is nowhere in that flow that has the option to create a new repo. As we cannot have detailed screenshots, the name of your Jira instance, or the name of your GH org or repos (which means I can't use logs to help look for issues) I need each step to be as detailed as possible.


Your steps to reproduce (please answer questions in bold):

1. Connect the app to any GitHub repository (note the repo for later) - in my case I selected to create a new repository. **Where did you choose to create a new repository?**
2. Check the project's Code section and note the GitHub cards there, including the one that links out to your GitHub repo above
3. Now try to change the repository to which the app is pointed... This is not possible. **How are you trying to change which repo the app is pointed to?**
4. Also at this point I realized my mistake, and I deleted the repository that was created by the app. However this has little no effect on the following. **Creating a repo in our app is not a feature. Repos can only be created in GH. Our app simply sends requests to GH, gets repo data for a given org, and then sends data to Jira. Can you try and explain this more?**
5. Disable Code in the project settings. **This is a feature of Jira, not our app and I am not sure how to disable this. Can you please give more details?**
6. Uninstall the app from Jira
7. Remove the app from GitHub. Github Organization > Settings > Installed GitHub Apps > Jira > Configure > Danger Zone "Uninstall"
8. Check Jira and the GitHub cards are gone from the Code tab <-- this is expected
9. Reinstall GitHub for Jira app. **Are you installing from Jira or from GH?**
10. Connect the app to GitHub accordingly and (important!) give permissions to Selected Repositories not including the one you originally connected to in the very first step above
11. Check your project's Code section - the cards you noted from above (GitHub connected and Repository link) have returned, even tho we have not given permissions to the connected repository!

**Comment by rachellerathbone** [comment] 2021-09-27 07:01
Me again. Would you prefer to open a support ticket via https://support.atlassian.com/? That way your issue won't be public facing and may mean you can share screenshots & other data. The issue will be forwarded to my team and, with the extra info, we will be better able to assist you.

**Comment by monkishtypist** [comment] 2021-09-27 16:04
As I mentioned previously, I _created a new project_ from scratch. I am attaching more screenshots below. In [Screen 1] you can see the default checkbox to "connect repositories" and in [Screen 2] you can see the "create a repository" checkbox (all 3 were checked by default). I originally neglected to read the "create" part and thought this would prompt me to choose. Also, the organization listed by default was not the correct organization, but in fact was one that I had not even given permissions to. Hope this is more helpful.

<img width="981" alt="Screen Shot 2021-09-27 at 8 57 05 AM" src="https://user-images.githubusercontent.com/7469173/134943719-383bef5d-2115-4d16-96ae-e0f3cc5e1ce3.png">

<img width="977" alt="Screen Shot 2021-09-27 at 8 58 44 AM" src="https://user-images.githubusercontent.com/7469173/134943747-be276355-157a-4b57-9972-e0c27179da0f.png">

I am not opening a support ticket specifically because I believe this will be helpful to others dealing with this issue. Thanks.

**Comment by rachellerathbone** [comment] 2021-09-29 00:07
Hey @monkishtypist. Thanks for the additional info. The reason why I was confused is that the feature you're using isn't a part of our github-for-jira app but instead a part of Jira itself (and is also something I've never personally used so wasn't able to make the connection). I found out that the team that built this has already identified this as an issue as multiple customers have reached out to them seeking a resolution. 

Currently, I only have internal Jira tickets but am trying to find out if there is a public-facing one that I can share here so you can track the work that team is doing.

**Comment by KAbakumovAtl** [comment] 2021-10-01 05:23
Hi @monkishtypist, we have investigated the problem and found that it is a bug on the Jira side. The "Create Repository" feature doesn't involve the GitHub App, it is a separate flow. I had a discussion with the responsible team and we've created a public issue regarding this bug: ​https://jira.atlassian.com/browse/JSWCLOUD-21944

You can track the progress on this problem in that Jira ticket. Hence we can't do much on the GitHub App side about it I am closing this issue.

Thank you for identifying the problem and helping us to improve!

**Closed by KAbakumovAtl** 2021-10-01 05:23 UTC
