### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by eugene00x7** [atlassian/github-for-jira#897] opened 2021-11-08 21:05 UTC
Hi support,

I'm trying to connect organization. Once I got to the screen where I'm asked to chose GitHub Organization and I'm clicking on my organization, I am getting redirected to this page https://github.com/organizations/CGS-Canada/settings/installations/20588817 which returns 404 error. Please advice how to overcome this issue.

Thanks,
Eugene

**Comment by rachellerathbone** [comment] 2021-11-08 22:31
Hey @eugene00x7. What browser are you using?

**Comment by mboudreau** [comment] 2021-11-08 22:57
Could you please take some screenshots of your path to that 404 page?  Thanks.

**Comment by eugene00x7** [comment] 2021-11-08 23:28
Hi Rachelle,

I'm using Google Chrome Version 95.0.4638.69 (Official Build) (64-bit)

Eugene

**Comment by eugene00x7** [comment] 2021-11-08 23:42
Hi Michael,

Please find screenshots attached to this email. Hope it helps.

Thanks,
Eugene

**Comment by mboudreau** [comment] 2021-11-09 00:46
@eugene00x7 Hey mate, your attachments on the email don't come through to Github for some reason.  Could you please add them via your browser?  Thanks.

**Comment by eugene00x7** [comment] 2021-11-09 01:08
![Screen1](https://user-images.githubusercontent.com/93925553/140843064-4a012cb2-e5a6-4cbd-9ca4-5455bf32da63.JPG)
![Screen2](https://user-images.githubusercontent.com/93925553/140843071-308c2038-9d8b-4125-9a48-819fb8f6a70c.JPG)
![Screen3](https://user-images.githubusercontent.com/93925553/140843086-3a306c54-a8ea-447a-812c-bb330c546e6b.JPG)
![Screen4](https://user-images.githubusercontent.com/93925553/140843089-7b617149-a174-42fe-a4ab-8d657c514328.JPG)

**Comment by eugene00x7** [comment] 2021-11-09 01:09
Hey mate,

Done. Screenshots are available in the thread on the site.

E

**Comment by mboudreau** [comment] 2021-11-11 22:32
@eugene00x7 I think we figured out what's going on.  The issue is 2 pronged:

1. You're currently seeing an old version of the UI which had some bugs in it.  We've not enabled your instance to show the new UI (shiny!) which shouldn't have this issue.
2. You don't seem to be an admin for this organization, hence the 404 page.  Github by default shows 404 when you don't have permissions to view something.  It was our fault that you got to that stage (again, old UI had bugs).  I'd recommend you either ask someone who's admin in the org to do the change you seek or ask to have your permissions upgraded to admin.

I hope this helps. Please let us know how you go.

**Comment by mboudreau** [comment] 2021-11-22 01:13
@eugene00x7 quick question, do you have IP allowlisting enabled?

**Comment by rachellerathbone** [comment] 2021-11-29 00:43
@eugene00x7 so we can assist you, please see the question above and let us know if you have this enabled.

**Comment by mboudreau** [comment] 2021-12-07 05:30
@eugene00x7 Any updates on this?  We've released a few fixes since the last reply which might have solved your issue.  Could you please try again and let us know?  Thanks.

**Comment by mboudreau** [comment] 2021-12-13 22:15
@eugene00x7 We're fairly sure we've fixed this issue.  I'll close it, but if this is still a problem, you can open the issue back up.

**Closed by mboudreau** 2021-12-13 22:15 UTC
Labels: awaiting response

**Comment by eugene00x7** [comment] 2021-12-14 12:42
Hi Michel,

Thank for fixing the issue.

Thanks,
Eugene
