### ISSUE TITLE
Can it keep the JIRA issue "in progress" when a PR is merged?

### ISSUE THREAD

**Issue by brandonvin** [atlassian/github-for-jira#296] opened 2019-11-15 17:51 UTC
Hi, sometimes a JIRA issue takes more than 1 pull request to fully resolve it. I'd like to be able to reference the issue number in each of these pull requests to fully document the work. However, the first pull request in the series that gets merged will immediately resolve the JIRA issue. In the cases when this is known ahead of time, is there a way to tell JIRA integration to keep it "in progress" for certain pull request merges?

**Comment by rachellerathbone** [comment] 2021-05-17 23:14
Hi @brandonvin. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

I've flagged this with the 'to-triage' label so my team can discuss. We'll keep you posted on the status of this.

**Comment by rachellerathbone** [comment] 2021-10-04 23:27
Hey @brandonvin. The team discussed this functionality and determined that this behaviour would go against the intended behaviour of the app. Our recommendation (something we do here at Atlassian) is to break Jira issues down into smaller issues/subtasks so that each issue can be targeted by 1 pull request.

Sorry that we aren't able to update the app to meet your needs. Going to close this issue now but please let me know if you need help with anything else.

**Closed by rachellerathbone** 2021-10-04 23:27 UTC
Labels: to triage
