### ISSUE TITLE
Github PR status not syncing to Jira

### ISSUE THREAD

**Issue by brianelliott-wt** [atlassian/github-for-jira#657] opened 2021-08-26 15:38 UTC
We've had a few instances where the PR status in Github is not syncing back to Jira and updating the status in the Jira ticket. We've set up some workflows that require the PR to be merged before the ticket can be moved to done, and its forcing us to disable these workflows.

Github app version:  1.1.3-AC
This is running on Jira Cloud

I'm unsure of how to troubleshoot this or find any error logs and would be happy to provide more information if needed.

**Comment by mboudreau** [comment] 2021-08-30 01:42
@umeshkumhar Can you please confirm that this is still happening?  If so, we'll monitor your domain for when the problem arises so we can decipher the cause.  Thanks.

**Comment by rehangit** [comment] 2021-08-31 15:35
This is still happening. Many synchronisation issues:
* Some branches with ticket number in the name are not picked up 
* Some tickets showing main/master as linked branch
* PR is open but not detected by jira
* PR is merged but Jira reporting open.

![image](https://user-images.githubusercontent.com/16896437/131531425-6c84b29c-09ad-48f7-bc59-d7cee37a4e15.png)
---
![image](https://user-images.githubusercontent.com/16896437/131532277-3f14ca1a-a32f-4a18-bc90-c9d55d1a588f.png)
All the PRs shown OPEN are actually merged.
![image](https://user-images.githubusercontent.com/16896437/131532426-ca11b3ad-1925-47ed-a4c8-d53157561211.png)

**Comment by brianelliott-wt** [comment] 2021-09-03 19:50
I believe this was fixed for our instance of Jira Cloud. I've updated the github plugin to the latest version and also did a normal sync within the github app config page after updating.

I've heard from our teams that the statuses are updating/syncing correctly now.

**Comment by thombergs** [comment] 2021-09-03 20:12
@brianelliott-wt thanks for the confirmation!

We've released a fix 11 hours ago, see this comment: https://github.com/atlassian/github-for-jira/issues/674#issuecomment-912404171.

**Comment by rachellerathbone** [comment] 2021-09-29 23:20
Hi @brianelliott-wt just checking in to see if this issue was resolved for you or if you still need assistance.

**Comment by rachellerathbone** [comment] 2021-10-05 00:48
Hey @brianelliott-wt. As we believe this issue has been resolved I'm going to go ahead and close this issue. Please feel free to reopen and reach out again if you continue to have issues with this.

**Closed by rachellerathbone** 2021-10-05 00:48 UTC
Labels: bug, awaiting response
