### ISSUE TITLE
JIRA Issue number not being parsed from commit body in PRs

### ISSUE THREAD

**Issue by sarodspirit** [atlassian/github-for-jira#1024] opened 2022-01-10 12:42 UTC
Hello! 

Is there any chance commit in pull requests are only being parsed if they are part of the commit message 1st line ? 
Our commit messages created by [commitlint](https://github.com/conventional-changelog/commitlint) have the following structure

```
build: Update PR Title Action

Update PR Title Action

PA-1045
```
where PA-1045 is an existing issue in JIRA, but unfortunately they are not being associated with the Jira Ticket, though commits do show up in the development tab.

In order to try and keep our commit message styles we've created a github action to parse the jira key and add it to the PR title, but in opposition to when done by a user, when github-actions bot updates the PR title, the jira sync workflow is not triggered.

Any workarounds to keep our commit style and have pull requests appear on JIRA ?

**Comment by mboudreau** [comment] 2022-01-11 07:10
Hm, looking at the logs, it seems like it's skipping your payload but we're not currently logging the payload at this moment.  Let me add that in and see what's going on.

The code itself to find an issue key is pretty dumb, it's simply a regex of `/[A-Za-z0-9]+-[0-9]+/g` and should match _anywhere_ in the commit message, even across multiple lines.  

Let me investigate this further and add more logging to see if we can get to the cause of this.

**Comment by mboudreau** [comment] 2022-01-11 07:15
Oh wait, I might have misread.  So the commits work and show up in JIRA, but it's the PR you're having issues with?

The PR won't be associated automatically based on the commits.  The PR itself needs to have the jira ticket number in the title or body for it to associate to the ticket.  The reason for this is we can't assume that a PR is associated to a ticket because of a single commit as it could be from a merge commit not related to your work.

Let me know if this makes sense.  Thanks.

**Comment by sarodspirit** [comment] 2022-01-11 09:06
@mboudreau thanks for your reply.
The PR has the ticket number in the body, the jira ticket number gets linkified properly.  It's just not a one liner or on the first line as shown in my example previously.

**Comment by rachellerathbone** [comment] 2022-01-11 22:50
Hey @sarodspirit. We recently rolled out an update for this. Can you please test it out and let me know if it works now?

**Comment by sarodspirit** [comment] 2022-01-12 00:01
@rachellerathbone it is, thanks. Im curious can you please point me to the PR fixing this ?

**Comment by mboudreau** [comment] 2022-01-12 03:53
@sarodspirit it would be this one:  https://github.com/atlassian/github-for-jira/pull/993

It's been merged for a while, but I don't think we enabled it for everyone until recently.

**Closed** 2022-02-11 02:34 UTC
Labels: bug, awaiting response
