### ISSUE TITLE
Close Jira Issue by merging PR

### ISSUE THREAD

**Issue by clmz** [atlassian/github-for-jira#292] opened 2019-10-22 10:04 UTC
Hey guys,

is it possible to auto close a Jira issue (move it to column 'Done') by merging the respective PR in github? 
I tried "close [JIRA issue id]" but this doesn't work.
Any other solution?

**Comment by pjoe** [comment] 2020-02-25 12:59
I think the notation is something like:
```
[PRJ-123] #done
```
Where `done` should match the state the issue should go to

**Comment by usmonster** [comment] 2020-08-11 21:46
You can also set up a [workflow trigger](https://confluence.atlassian.com/adminjiracloud/configuring-workflow-triggers-776636696.html) directly on the transition in your project's Jira workflow. I wish it were something automatically configurable, but I opened #381 to at least document this as a possibility (even though it's not a feature specific to the GitHub integration).

**Comment by shilpaairi** [comment] 2020-08-11 22:48
Hi there,

You can use [Automation for Jira](https://support.atlassian.com/jira-software-cloud/docs/automate-your-jira-cloud-processes-and-workflows/) for automating your workflows across multiple products. Please refer to [this](https://community.atlassian.com/t5/Automation-articles/New-automation-triggers-across-Jira-Cloud-Bitbucket-GitLab-amp/ba-p/1337351#U1378603) for a quick guide on Git triggers.

**Comment by JayNakrani** [comment] 2020-09-25 16:11
> I think the notation is something like:
> 
> ```
> [PRJ-123] #done
> ```
> 
> Where `done` should match the state the issue should go to

@pjoe : Have you seen this working?

I have tried several different things like `JRA-XYZ #resolve`, `JRA-XYZ #close` and `JRA-XYZ #finish-work` but it has never worked.

Looking at the code, I am not 100% sure if the action even triggers on `pull_request.merge` action because it's missing in https://github.com/integrations/jira/blob/f2c3568254d04a5439a469764863e2f4eb7b4d99/lib/github/index.js#L28

**Comment by pjoe** [comment] 2020-09-28 05:23
IIRC, for me it worked when adding a comment to the PR (as part of merging it). The `#state` much match the state you want the issue to go to, like the column on a board.

**Comment by rogerluan** [comment] 2021-03-18 17:23
@pjoe could you explain your solution better? Is it a standalone comment on the PR such as `JRA-123 #done`, or a "commit merge message" containing `JRA-123 #done`? Or `JRA-123 #done` in the PR description? 🤔

**Comment by pjoe** [comment] 2021-03-18 19:40
Mainly been using in the merge PR message, but would expect it to work anywhere (where smart commits works). I have found though that you may need to use the name of the transition, not the state (which is not always the same).

**Comment by rachellerathbone** [comment] 2021-05-17 09:24
Closing as the issue as it seems to have been addressed by suggestions in this thread.

**Comment by astleychen** [comment] 2021-05-25 09:25
It seems broken lately and looks like a regression as it worked before(5~7 days ago).

Steps to reproduce:
1. Create a merge commit for PR
2. Keep the merge commit title as is, e.g. `Merge pull request #<issue> from username/repo`
3. Edit commit description with Smart Commit syntax. For example: `JIRA-1234 #close commit body`

It can close Jira issue if you create a normal commit with exactly same commit message as steps above, but will fail if that commit is a merge commit.

**Comment by astleychen** [comment] 2021-05-25 10:15
@rachellerathbone Could this be a regression from recent changes on https://github.com/integrations/jira/pull/456 ?

**Comment by mboudreau** [comment] 2021-05-25 11:58
I'm reopening this so we can investigate, but yeah, very possible that there's a regression because of a bad merge.  We'll have to add some tests on this so it doesn't happen again.  Thanks for letting us know.

**Comment by rachellerathbone** [comment] 2021-05-25 22:19
Hey @astleychen. Outside of some linting and tests, the only real change to this was the addition of the MERGE_COMMIT flag. This flag allows Jira to differentiate between merge commits and regular commits. I'm fairly new to Atlassian but I'm guessing this might be intended behaviour in Jira. I'd need to follow-up with some people who work on Jira but, given the minor change that was introduced, it seems like that is the case. 

That said, I think it makes sense to keep supporting this functionality for our users so I think we'd need to determine if there's a way to support closing out issues on merge commits and the rendering accounted for in #456.

**Comment by astleychen** [comment] 2021-05-26 01:52
@rachellerathbone Thanks for your feedback. #456 provided a good way to distinguish type of commits in Jira, I totally agree to keep this functionality as is.

I've been using GitHub/Jira integration app and leveraging this feature(closing issue after PR merged) for months. Pretty sure it's a regression from recent changes. From my tests, parsing a multi-line `merge commit` message seems to be broken. The same commit message on a normal commit can successfully close the Jira issues.

**Comment by rachellerathbone** [comment] 2021-05-26 02:54
@astleychen I confirmed with the team that this is the expected behaviour for merge commits with Jira. Adding the `MERGE_COMMIT` flag actually fixed what would be considered a bug. Jira only allows for the transitioning of tickets for regular commits as a merge commit may have a multiple parents, each of which could reference multiple Jira issues. The implementation of blocking transitioning for merge commits (which we had missed in the app until recently) is to avoid unintended edge cases where a parent branch references an issue/s that a user doesn't want to close, but ultimately would be transitioned after the merge commit takes place.

However, my team are open to discussing this further but would like to know more about why this functionality is beneficial for you and what value it adds to your workflow.

**Comment by astleychen** [comment] 2021-05-26 04:26
@rachellerathbone Thanks for your clarification on this intended behavior change.
In our current workflow, when we start a new task, we will create a Jira issue to track task progress and provide update through Smart Commit. When a pull request is reviewed and able to merge on GitHub, it will be merged by creating a merge commit with commit message as below:

```
Merge pull request #XX from username/branch

JIRA-1234 #close add new features
```

The first line is automatically added by GitHub and second line is added by pull request title.
The developer adds #close command to pull request title if he/she wants to close JIRA issue after PR is merged.
With behavior change, we will need to manually copy `JIRA-1234 #close` from PR title and paste it to front of merge commit title. The step could be easily skipped for code merger(developers or reviewers) and hard to control by PR author.
The workflow might not be normal as majority, any suggestions are welcomed. Thanks.

**Comment by rachellerathbone** [comment] 2021-05-27 05:35
@astleychen I've added the 'to triage' label so that my team knows more discussion is needed around this. We'll keep you posted.

**Comment by pkania** [comment] 2021-06-02 14:49
We, too, have depended on this now broken feature. We only want to #resolve issues once the changes have been merged into a "public" branch. We *only* add the smart tags to merge commits. If someone does not want the transition to occur because of a change in a parent commit, then don't put the transition tag in the parent commit (you can use #comment for example). Or amend the commit with a new message before merging.

The suggestion that we can workaround this with custom automation is not satisfactory, IMO. We had custom automation todo this before the plugin was available but ripped it out in favor of the vendor supported solution once we were satisfied that the GitHub plugin did what we wanted. Now after years of use, you change the behavior and tell us we can fix it ourselves if we don't like what you have done.

**Comment by mboudreau** [comment] 2021-06-03 02:44
@pkania Thanks for letting us know.  We'll re-assess the functionality soon.

**Comment by rachellerathbone** [comment] 2021-06-04 02:13
Hey @pkania. Apologies that this bugfix has removed functionality you were relying on.  

Just wanted to update you and let you know that we are actively investigating how to solve this so we can support the intended functionality (current implementation) as well as the functionality that our customers adopted into their regular workflows for merging.

**Comment by thombergs** [comment] 2021-06-11 04:37
Hey @pkania and @astleychen,

sorry for the wait, we discussed this issue in the team. I would like to understand your use cases better and why the [Automation feature in Jira](https://community.atlassian.com/t5/Automation-articles/New-automation-triggers-across-Jira-Cloud-Bitbucket-GitLab-amp/ba-p/1337351#U1378603) isn't working for you. In our view, the Automation feature is more powerful and convenient than using Smart Commits keywords in commit messages, but I might not have understood your use case correctly. 

I understand that you only want to transition Jira issues when a PR is merged into a specific branch. Let me outline how this can be solved with an automation rule. This can be done with a "pullrequest merged" trigger and a condition that checks that the `{{pullRequest.destinationBranch}}` matches a certain pattern (for instance `^.*master$`, if we want to transition the issue after a merge into the `master` branch):
  
![image](https://user-images.githubusercontent.com/1363578/121630939-7972d600-cac1-11eb-9509-12d84124afd2.png)

Solving it this way has the added benefit that we don't need to "pollute" our commit messages with keywords like "#resolve" or "#close". You can find more information about the variables you can use in the [docs](https://support.atlassian.com/jira-software-cloud/docs/smart-values-development/).

Would that work for you? If not, why not?

**Comment by astleychen** [comment] 2021-06-11 08:53
> Hey @pkania and @astleychen, 
> Would that work for you? If not, why not?

@thombergs Thanks for your valuable feedback. JIRA Automation rules is awesome (Sorry, I'm not that familiar with ALL Jira features) and totally fit our need. With that, we can have full control on actions whenever a PR is merged and even more. Now, we don't need to append #transition command in PR title as well as no need to create a named transition to trigger closing event. Appreciate for your help.

**Comment by pkania** [comment] 2021-06-11 14:50
@thombergs We do not use pull requests for all our repos. We use a different review process for some of our most important repos. Changes are merged into a public branch and pushed. The problem is that you no longer transition based on merge commits. Again, those are the only commits where we use the smart keywords in the commit messages.

A trigger like you suggest would require parsing the commit messages for the smart keywords to know which issues, if any, to resolve.

We've made the the smart commit keywords part of our tooling. Moving away from their use would require additional development effort.

Using triggers in addition to the GitHub integration would make the system more fragile and increase the maintenance effort.

**Comment by thombergs** [comment] 2021-06-15 04:02
@pkania this would actually be possible with Jira's Automation. You can add a condition to check if the commit is a merge commit and another condition to check if a certain keyword is included (the keyword will be found if it's in the first 50 characters of the commit message, I believe):

![image](https://user-images.githubusercontent.com/1363578/121990856-d92ef100-cde1-11eb-98ad-bf6fb7090474.png)

However, a merge commit currently doesn't seem to trigger an Automation rule, either, so I'm currently following up with the Automation team on this. I'll be in touch when I have more information about this.

**Comment by rachellerathbone** [comment] 2021-10-04 23:23
Hey @pkania and @clmz. Given that it has been a few months since we've heard anything on this issue, I'm going to go ahead and close it. Please feel free to reopen if your issue hasn't been addressed or you would like help with something else.

**Closed by rachellerathbone** 2021-10-04 23:23 UTC
Labels: stay tuned

**Comment by Hronom** [comment] 2024-02-27 02:27
What people wants here is basically this [functionality of GitHub](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword), please can you help here how to do this with Jira and GitHun integration?

**Comment by robynlarsen** [comment] 2024-03-11 01:37
++ to @Hronom 's suggestion. I'm down the rabbit hole and currently moving from GH issue/projects to JIRA at a new company. It's unclear to me why the JIRA experience requires so much more for kanban automation.
