### ISSUE TITLE
Can't see anything on JIRA Get Started Page

### ISSUE THREAD

**Issue by nrafal** [atlassian/github-for-jira#391] opened 2020-10-09 12:37 UTC
Hi! I can't install JIRA add on. I've stared process from JIRA didn't work, started from GitHub, same. I have error on Get Started Page in JIRA - I see empty page. 

This is what I see in Firefox debugging tools, 404 error while loading APP from jira-integration-production.herokuapp.com
![obraz](https://user-images.githubusercontent.com/9462330/95583720-d69f1f00-0a3c-11eb-96a4-efa7c772f7af.png)

**Comment by nrafal** [comment] 2020-10-09 12:47
I've already tried reinstalling a couple of times and it didn't help

**Comment by abichandani** [comment] 2020-11-08 18:50
I am also facing the same issue. Tried reinstalling many times. Didn't work!

**Comment by nrafal** [comment] 2020-11-09 13:05
@abichandani I've written to support using marketplace https://marketplace.atlassian.com/apps/1219592/github-for-jira?hosting=cloud&tab=support and they have resolved my issue pretty quickly, although I am not aware if it was a general fix or only my case.

**Comment by rachellerathbone** [comment] 2021-05-17 10:41
Hi @nrafal. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

This is an issue our team is actively looking into. It's proving to be a hard issue to reproduce but will continue to be something we work towards resolving. Stay tuned.

**Comment by JadedEvan** [comment] 2021-06-22 13:17
Just wanted to chime in on this - my organization is currently facing the same issue. Symptomatically this seems to be a 404 response from Github when requests are made from Jira (OP's screenshot shows this). Atlassian had responded to me saying there might be a null OAuth ID on Github's side.

I have contacted both Atlassian and Github - they both pointed the finger at each other and said to ask the other party. I have also tried revoking permissions and reinstalling, none of that seemed to work.

I will say this _did work_ at one point in the past - probably going back to October of 2020 or earlier. Don't know what's changed since then.

**Comment by mboudreau** [comment] 2021-06-22 13:30
For those having the issue, are you using GitHub Enterprise? The only other reason I can think of is that the app doesn't have the permissions needed to do its job. Could you please get your GitHub org admin to check that the permissions are up to date for the app?

Thanks.

**Comment by rachellerathbone** [comment] 2021-10-05 00:19
Hey @JadedEvan, @nrafal and @abichandani. Given that there hasn't been any activity on this issue for a few months I'm going to go ahead and close this. Please feel free to reopen and reach out again if you are still having issues.

**Closed by rachellerathbone** 2021-10-05 00:19 UTC
Labels: awaiting response

**Comment by ChrisChiasson** [comment] 2023-10-11 04:46
I have this problem as well in Jira cloud. It never even gets to a stage where it will ask me about github at all, but if it matters we use regular GitHub. I am using it in private browsing because I am forced to (don't ask). The errors that appear to be unique to the getting started page are as follows in the screenshot.

![image](https://github.com/atlassian/github-for-jira/assets/11857915/0f8af0ac-13f3-4e6e-9ebb-00992fa13cdc)

**Comment by ChrisChiasson** [comment] 2023-10-11 04:50
The problem from the prior post is probably going to become more widespread as google clamps down on cross domain operations, especially with the demise of 3rd party cookies next year. Probably needs a rewrite of this part. I also found a problem when using Chrome on android in desktop browsing mode (a place where I can get access to my company SSO in regular browsing mode)... it fails after hitting authorize in github when it loads this type of url:

https://github.atlassian.com/rest/app/cloud/github-callback?code=REDACTED&state=REDACTED

**Comment by krazziekay** [comment] 2023-10-11 23:08
@ChrisChiasson 
This seems to be a browser settings issue. In private mode, the option **Block third-party cookies and site data** is checked by default and that blocks the usage of `localStorage`. That explains why it wasn't working for you in private mode, but worked in non-private mode.
We'll push out a fix for this soon.

**Comment by ChrisChiasson** [comment] 2023-10-12 00:04
> @ChrisChiasson 
> This seems to be a browser settings issue. In private mode, the option **Block third-party cookies and site data** is checked by default and that blocks the usage of `localStorage`. That explains why it wasn't working for you in private mode, but worked in non-private mode.
> We'll push out a fix for this soon.

100% concur, and thank you @krazziekay
