### ISSUE TITLE
Implicit autolink references

### ISSUE THREAD

**Issue by usmonster** [atlassian/github-for-jira#373] opened 2020-07-02 15:31 UTC
This integration requires that [issue references](https://github.com/integrations/jira#link-issues-in-github) be surrounded by square brackets (`[]`) in order to link back Jira. This is a source of friction, and it works differently than other implementations of equivalent features (e.g. GitHub, Bitbucket, [GitLab](https://docs.gitlab.com/ee/user/project/integrations/jira.html#jira-issues), ...), where a simple mention of the Jira issue key will result in a link.

I know there's already a built-in GitHub feature for [autolinking](https://docs.github.com/en/github/administering-a-repository/configuring-autolinks-to-reference-external-resources), but it can often be tedious or infeasible to manually register and maintain them for every (Jira project ✖️ GitHub repository) for even medium-sized organizations.

I see that there are already some requests for improvements to the built-in feature that could make this slightly easier to do, such as [organization-level autolinking](https://github.community/t/would-like-to-see-autolink-references-configurable-at-the-organization-level/2808) or [API support for autolink configuration](https://github.community/t/support-autolink-reference-configuration-in-the-api/14614). This is fine, but would still require extra manual work or scripting that should probably just be built into the Jira integration already.

My request is for a feature that can coexist with the built-in autolinking, and which doesn't require bracketing issue references. Basically:
* Autolink any GitHub references to Jira tickets known to exist in connected Jira instances (could be simpler to not check for ticket existence, but only project existence)
* Any autolink rules registered via the built-in GitHub feature should override this behavior

Alternatively (probably worse design):
* Auto-register & manage autolinking rules in all Jira-integrated repos (one rule per Jira project)

Is either option feasible here? Without linking all references (not only those surrounded by brackets), it seems like an incomplete feature. Thanks!

**Comment by rachellerathbone** [comment] 2021-05-17 23:20
Hi @usmonster. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

I've flagged this with the 'to triage' label so my team can discuss. We'll keep you posted on the status of this.

**Comment by usmonster** [comment] 2021-05-18 10:15
Thanks for looking at this!

**Comment by ccrolf** [comment] 2021-08-06 05:33
Closing this as a duplicate of [this issue](https://github.com/atlassian/github-for-jira/issues/409#issuecomment-894003311). That project will cover designing a good and consistent way to linkify issue references in GitHub.

**Closed by ccrolf** 2021-08-06 05:33 UTC
Labels: to triage

**Comment by usmonster** [comment] 2022-01-28 13:49
@ccrolf Sorry to come back to this after so long, but I only now noticed that the issue you linked to, about linking from commit messages, is actually unrelated to my request, which is about loosening the syntax requirements.

To simplify my request, it's to detect both `PROJ-123` and `[PROJ-123]` as hyperlinkable issue references, as long as there is a `PROJ` project in the connected Jira instance. Please let me know if this can be reopened, or if there's another open issue that covers this request.

Thanks!

**Comment by ADTC** [comment] 2023-03-13 11:20
@ccrolf can we re-open? I also find it so odd that we have to add square brackets. I expected it to work with just the mention of issue key, **without having to set up autolinking ourselves in every project** (which BTW is only available for Paid plans 😢 so it's completely _not a solution_ for those just using the Free plan)

In fact, I wasted time trying to get the unfurling of links to work because this requirement of square brackets isn't even properly mentioned in the `README` or wherever the feature is mentioned. The symbols are there, but there's no explicit warning that they must be added.
