### ISSUE TITLE
cannot create branch within Jira 

### ISSUE THREAD

**Issue by devnetspot** [atlassian/github-for-jira#923] opened 2021-11-17 19:06 UTC
After successful integration Jira with my Github organization, now when I create task on Jira, after clicking on the task I should be able to create branch under development section on Jira, but I cannot create branch.

Screenshot:

<img width="1743" alt="Screen Shot 2021-11-17 at 10 01 12 PM" src="https://user-images.githubusercontent.com/94528168/142266086-7f6523a1-43b2-4111-872b-2d2d62f223f7.png">

**Comment by mboudreau** [comment] 2021-11-18 23:30
Duplicate of https://github.com/atlassian/github-for-jira/issues/402

Closing issue.  Please bring up concerns in the original one.

**Closed by mboudreau** 2021-11-18 23:30 UTC
Labels: duplicate
