### ISSUE TITLE
Internal Server Error when connecting GitHub organisation

### ISSUE THREAD

**Issue by awesome-Leni** [atlassian/github-for-jira#1369] opened 2022-07-14 13:29 UTC
Hello!

I'm getting 500 Internal Server Error when connecting GitHub organisation.
GET https://github.atlassian.com/github/configuration gives 500.

Could you help me to connect my GitHub organisation?

**Comment by yersoy** [comment] 2022-07-28 11:16
i couldnt be able to do. it think its broken.

**Comment by mboudreau** [comment] 2022-07-28 12:32
@awesome-Leni what is your jira url?  I'll look at the logs.  Do you have IP Allowlisting enabled in your github org?

**Comment by Ritma-Teknoloji** [comment] 2022-07-28 12:36
IP allowlist is a premium feature :/

**Comment by mboudreau** [comment] 2022-07-28 13:23
@Ritma-Teknoloji you don't need it, the problem is often because IP Allowlisting is enabled and not configured properly.  If you don't have it enabled, there shouldn't be any major issue unless you're not the admin of the github organization.

**Comment by rikur** [comment] 2022-08-10 11:48
`https://github.atlassian.com/github/configuration` gives 500 to me as well. Shame, wanted to give Jira <> Github a spin.

**Comment by atrigueiro** [comment] 2022-08-23 04:21
Hi @awesome-Leni @yersoy @Ritma-Teknoloji and @rikur,
You'll need to go through the right flow of installing the GitHub for Jira App in your Jira and then proceed with the installation flow for it to make it work.

<img width="1353" alt="Screen Shot 2022-08-23 at 2 07 59 pm" src="https://user-images.githubusercontent.com/58801956/186068138-86b8c1be-6fec-4927-a6fb-03c1c72fa7e0.png">

After installing the app, from the page above, when you click `Connect GitHub organization` we'll redirect you to the `github/configuration` URL using your current Jira host. Directly navigating to the `https://github.atlassian.com/github/configuration` link returns a 500 because we don't know the Jira Host you're trying to install the app.

As Michel mentioned above, if you don't have IP Allowlisting enabled, there shouldn't be any major issue unless you're not the admin of the GitHub organization.

Could you please try to install the app again and, if not successful, could you send your Jira Hosts so we can investigate further on our end? Thanks!

**Comment by rachellerathbone** [comment] 2022-10-19 04:12
Hey @awesome-Leni @yersoy @Ritma-Teknoloji and @rikur. As we haven’t heard from you in almost 2 months, I’m going to go ahead and close this issue. Please feel free to reopen if you still need assistance.

**Closed by rachellerathbone** 2022-10-19 04:12 UTC
Labels: awaiting response

**Comment by dtip** [comment] 2022-10-20 10:52
@rachellerathbone I had this problem today. Installed the Atlassian-side app, clicked the "Connect GitHub organization" button shown in @atrigueiro 's screenshot above, it tried to take me to GitHub to authenticate and get set up but it caused an error. First time I tried it said "Jira Host url is missing", then when I went back a retried I hit the internal server error. The workaround was to go to the GitHub org I wanted to link, install the GitHub-side app there manually first, then go back to the Atlassian side to link the two.

Seems like there's a bug in there somewhere, but if you want a quick "fix" you should update the messaging during the Atlassian-side app install to make it clear that we need to manually install the GitHub-side app before it's possible to connect Jira to GitHub.

**Comment by antonengelhardt** [comment] 2023-04-19 11:43
@awesome-Leni Can you explain how you got this to work again? I'm also getting the "Unauthorized" message

**Comment by awesome-Leni** [comment] 2023-04-19 11:49
> @awesome-Leni Can you explain how you got this to work again? I'm also getting the "Unauthorized" message

Did you try following the steps I described in my comment above?
I don't think my explanation can be more detailed than what I already wrote.

**Comment by antonengelhardt** [comment] 2023-04-19 13:03
@awesome-Leni Thanks. I got it now. It was a weird issue with my Browser.
