### ISSUE TITLE
GitHub For Jira is not syncing taking hours and hours and still not done

### ISSUE THREAD

**Issue by cdeshaw** [atlassian/github-for-jira#638] opened 2021-08-23 22:11 UTC
GitHub For Jira is not syncing taking hours and hours and still not done. Can someone please help, all I want is to see my commits on Jira tickets.

**Comment by thombergs** [comment] 2021-08-23 23:33
Hey @cdeshaw,

yeah, the syncing can take very long, especially for big GitHub organizations with a lot of (big) repositories. We're going to work on making that less painful soon!

However, to clear up a common misconception: the integration is already working when the sync is not complete! If you push a commit or branch or create a pull request in a GitHub repo that is connected, and use the proper Jira issue key in the commit message / branch name / pull request title, they should show up in Jira! The sync is just a "backfill", i.e. it loads historical commits etc. from GitHub and sends them to Jira. 

Hope that helped, please let me know if you have any more questions!

**Comment by cdeshaw** [comment] 2021-08-23 23:46
We are not large we only have 49 repositories but most of those are pretty small. Something is wrong because it wasn't doing this before. Our commits were showing up on Jira Issues with no problem last week, than today one didn't show on a Jira Issue, so the only thing I could think of was to try syncing again.

**Comment by cdeshaw** [comment] 2021-08-23 23:47
And yes I checked 3 times the commit message is correct for it to show on a Jira Issue.

**Comment by dswindle** [comment] 2021-08-24 01:11
I'd like to chime in that we've used the integration for years, mostly without issue. We just started noticing this same behavior today. For us, it's very sporadic. I can update PR 1234 and nothing shows up in Jira. Then I immediately update PR 456 and all the updates show in Jira.

**Comment by mvn-tony-hn** [comment] 2021-08-24 01:22
It has not working from the maitenance until now. I have to update all of my tasks by hand. The trigger of commit and PR created automation... didn't work anymore. Please fix it asap

**Comment by thombergs** [comment] 2021-08-24 01:34
@cdeshaw @dswindle @mvn-tony-hn thanks for your input. It might have something to do with the migration we did over the weekend, then. We're actually seeing some errors in the webhook processing, but have yet to figure out if this is what you're seeing and why this is happening. 

If any of you could provide their Jira URLs, that would help us narrow down the issue (i.e. `https://xyz.atlassian.net`). If you're not comfortable sharing that here, feel free to raise a support issue [here](https://marketplace.atlassian.com/apps/1219592/github-for-jira?hosting=cloud&tab=support) and link this GitHub issue, so the support team knows they can contact me.

**Comment by majsty** [comment] 2021-08-24 13:42
I am also seeing this. Triggering a full retry via https://xxxx.atlassian.net/plugins/servlet/ac/com.github.integration.production/github-post-install-page works, but new commits/branches/pull requests do not appear in the Development section.

**Comment by hschne255** [comment] 2021-08-24 14:16
Also seen yesterday. Some worked right away, others I ended up manually moving in Jira b/c i didn't see the update go through.

**Comment by cdeshaw** [comment] 2021-08-24 14:43
I let the sync run overnight and it failed.

**Comment by cdeshaw** [comment] 2021-08-24 15:21
> 
> 
> @cdeshaw @dswindle @mvn-tony-hn thanks for your input. It might have something to do with the migration we did over the weekend, then. We're actually seeing some errors in the webhook processing, but have yet to figure out if this is what you're seeing and why this is happening.
> 
> If any of you could provide their Jira URLs, that would help us narrow down the issue (i.e. `https://xyz.atlassian.net`). If you're not comfortable sharing that here, feel free to raise a support issue [here](https://marketplace.atlassian.com/apps/1219592/github-for-jira?hosting=cloud&tab=support) and link this GitHub issue, so the support team knows they can contact me.

The link you provided has s support link that links back to basically here. If you want I can email you or DM you somehow our Jira Address.

**Comment by adrianne-helpscout** [comment] 2021-08-24 15:34
@cdeshaw I work with @dswindle and here is  a sample issue where we are seeing the problem: https://helpscout.atlassian.net/browse/HSAPP-4654
I hope this helps. We can probably dig up some other examples if that would be useful. Just let me know.

**Comment by cdeshaw** [comment] 2021-08-24 15:43
> 
> 
> @cdeshaw I work with @dswindle and [here is a sample issue](https://helpscout.atlassian.net/browse/HSAPP-4654) where we are seeing the problem.
> I hope this helps. We can probably dig up some other examples if that would be useful. Just let me know.

Says my email doesn't have access to Jira on helpscout.atlassian.net.

**Comment by adrianne-helpscout** [comment] 2021-08-24 17:33
> Says my email doesn't have access to Jira on helpscout.atlassian.net.
 
 @cdeshaw Sorry about that. I meant to mention @thombergs instead. I've fixed the prior comment.

**Comment by cdeshaw** [comment] 2021-08-24 20:52
> 
> 
> @cdeshaw @dswindle @mvn-tony-hn thanks for your input. It might have something to do with the migration we did over the weekend, then. We're actually seeing some errors in the webhook processing, but have yet to figure out if this is what you're seeing and why this is happening.
> 
> If any of you could provide their Jira URLs, that would help us narrow down the issue (i.e. `https://xyz.atlassian.net`). If you're not comfortable sharing that here, feel free to raise a support issue [here](https://marketplace.atlassian.com/apps/1219592/github-for-jira?hosting=cloud&tab=support) and link this GitHub issue, so the support team knows they can contact me.

Is there any chance you could rollback your last code change? So this will work again?

**Comment by thombergs** [comment] 2021-08-24 21:00
@adrianne-helpscout thanks for the info! This will help us isolate the error.

@cdeshaw feel free to send me your Jira URL to thombergs@atlassian.com and we'll look into it.

> Is there any chance you could roll back your last code change?

We'd like to, but it's not so simple, sadly. We have migrated the service from GitHub's infrastructure into Atlassian's infrastructure, so a lot more than just code changed. We're looking into this with top priority, though. We can see intermittent webhook failures, but we haven't identified the cause for them, yet. We'll keep you updated with any progress.

**Comment by thombergs** [comment] 2021-08-25 07:48
Hey all,

we've identified and fixed an issue that caused commits, branches, etc. not to arrive in Jira when you have two or more Jira sites connected to the same GitHub organization. Was this the case for you? Did you have more than one Jira site connected to the same GitHub org?

Please let us know if you are still experiences these issues.

**Comment by cdeshaw** [comment] 2021-08-25 14:21
As far as I know we only have 1 Jira site connected.

**Comment by mvn-tony-hn** [comment] 2021-08-25 14:53
@thombergs 
Update for this:
1. I have many jira sites connect to one github organization
2. The github commit and pull request have worked fine on my jira site since yesterday night
3. But the deployment status (using circleci-orb-jira.status)  didn't seem work fine:
- I'm sure my branch name had issue key
- The deployment status return: `rejectedDeployments` on my circleci console then my issue couldn't receive the deployment status
The log as below:

This job is passing, however another job in workflow is success
Update Jira with status: successful for 370
Results from Jira: 
```
ERROR: unknown association
{
  "acceptedDeployments": [],
  "rejectedDeployments": [
    {
      "key": {
        "pipelineId": "******",
        "environmentId": "******",
        "deploymentSequenceNumber": 370
      },
      "errors": [
        {
          "message": "No valid associations found for deployment"
        }
      ]
    }
  ],
  "unknownIssueKeys": [],
  "unknownAssociations": [
    {
      "associationType": "serviceIdOrKeys",
      "values": [
        ""
      ]
    }
  ]
```
I take many times to ssh into my circleci pipeline but not found any issue. 
I guess the function `post_to_jira ()` returned the wrong information
Please check it and investigate asap. Thank you!

**Comment by dswindle** [comment] 2021-08-25 15:06
We're still seeing the issue on our side. We only have one Jira instance connected to Github.

**Comment by thombergs** [comment] 2021-09-01 04:23
closing this issue, since the root cause has been fixed.

**Closed by thombergs** 2021-09-01 04:23 UTC
Labels: stay tuned
