### ISSUE TITLE
Look in PR body for issue keys

### ISSUE THREAD

**Issue by bkeepers** [atlassian/github-for-jira#119] opened 2018-10-15 22:18 UTC
Currently only looks in PR title, but I think it makes sense to scan the body as well.

cc https://halp.githubapp.com/inboxes/technical/labels/ecosystem-integrations-jira/discussions/35a63390d08211e89a1a7d72d9abdb35

**Comment by andymckay** [comment] 2018-10-17 22:39
Can I confirm that we should do this? The [DevInfo API](https://developer.atlassian.com/cloud/jira/software/rest/#api-rest-devinfo-0-10-bulk-post) allows us to post the title, but doesn't mention anything about the body in the API. We could do this by concatenating the title and body together (which is in the proposed) PR, but I wondering if that's the correct thing to do with the API.

**Comment by KAbakumovAtl** [comment] 2018-10-18 02:02
Technically it is possible to do with DevInfo API without including PR's body in the request. All you need is to include appropriate issue keys in "issueKeys" array parameter of this PR.

**Comment by tcbyrd** [comment] 2018-10-18 13:11
@KAbakumovAtl Just to be 💯clear on the ask, is this something that was supported before in the DVCS connector or would this be considered new functionality if we enable it in the new integration? I think we mainly want to know if this is something we should consider adding to the sync job or if it makes sense to only worry about for new data.

**Comment by blidgey** [comment] 2018-10-18 14:01
We have been using the Git Integration for Jira plugin from BigBrassBand that does this and sync's with old data.

**Comment by jarrodholliday** [comment] 2019-03-06 07:18
I second this and looking at commit messages in the PR for issue keys as well. 
Previously with DVCS connector it worked for us and now after updating to the new App Integration it's broken.

**Comment by zalloy** [comment] 2019-03-28 20:42
Any update on this? We also used to use the DVCS connector, and this used to work with that, but after changing to this integration it stopped working. It's preventing our deployment PRs from showing up in Jira, which is very annoying because it makes it hard to tell what's going on. Ideally, I would like to be able to use a JQL query for a given PR title in Jira, and have all the issues in that PR (we do use smart commits) show in the search results.

**Comment by tcbyrd** [comment] 2019-03-29 15:00
Hi @zalloy! Just to confirm, are you wanting to look in both GitHub Issues and Pull Request bodies for issue keys, or would it be sufficient to look in just the main body of the Pull Request? Pull Request body and issue comment bodies are separate events.

> preventing our deployment PRs from showing up in Jira

Can you explain more about what you mean here? I don't have a clear understanding of the difference between a regular PR and a "deployment" PR.

**Comment by zalloy** [comment] 2019-03-29 15:37
@tcbyrd The way it was working before, with the DVCS connector, it would work something like this:

- Engineer would create a PR to merge from master to staging, that contains all the commits that we planned to release, that passed preliminary QA on master. In this case, the PR title would be something like "Release [date and/or number] - master -> staging" and the PR body would contain a template that may or may not be filled in, but usually does not contain a list of the Jira issues in the PR.
- That PR would then show up in the development pane in Jira for each Jira issue that had commits in that PR, as long as the commits were done using smart commit syntax.
- After testing was done in staging, and we were satisfied that everything is good to go, Engineer then created a PR with a title something like "Release [date and/or number] - staging -> production" and that PR would be done the same way as I described before, and would also show on the affected issues in Jira.
- We're only using Jira for issue tracking, rather than Github's built-in issues tracker. 

The problem is that we can't put all the affected issues in the PR title, and we also can't count on Engineering to manually put a list of the Jira issues in the PR body/comment (because there isn't enough room, and it also makes it hard to figure out what the PR is for unless you view it on Github), because that tends to leave a lot of room for error (something always manages to get overlooked).

I'm not sure if this is the best place for that, or whether the issue I'm experiencing is separate from this one. If this is a separate thing, I can go ahead and create a separate issue here for that. Ideally, I would just like this functionality to work the same way as it used to with the old connector.

**Comment by TheJessle** [comment] 2020-03-11 18:48
I'd like to know if this issue is, or is planned to be, fixed soon. I've got a team that used this integration prior to the changes and I've revived the connection. Just need to know what I'm reporting to them as far as work process.

**Comment by makshark** [comment] 2020-03-24 18:34
Hi, any progress on this one? It is really needed for our team, as we decided to migrate from bitbucket to Github. Thx.

**Comment by mrcarriere** [comment] 2020-07-06 11:30
In case the team working on this isn't aware: this is functionality that **used** to exist, and was lost at some point. Please add this feature back.

**Comment by pgrantmartello** [comment] 2021-03-01 14:47
Hi! Is this ever going to be fixed?

**Comment by pgrantmartello** [comment] 2021-03-01 15:26
I don't, and won't have time to, have an instance of JIRA running locally to develop this, but I did a bit of digging in case someone else wants to do the work and make a PR.

It seems that this is _supposed_ to happen already. Look here:

https://github.com/integrations/jira/blob/414bd9d917dea2625a12eb3495350fe7003efc24/lib/github/pull-request.js#L18

This seems like it's supposed to take in the PR body, [unfurl them](https://github.com/integrations/jira/blob/414bd9d917dea2625a12eb3495350fe7003efc24/lib/jira/util/index.js#L52) to look for any valid JIRA ticket numbers, and modify the body to turn them into links.

However, before it can run that bit of code, it's checking for a `jiraPayload` here: https://github.com/integrations/jira/blob/414bd9d917dea2625a12eb3495350fe7003efc24/lib/github/pull-request.js#L11

`jiraPayload` is a reference to a [method called transformPullRequest](https://github.com/integrations/jira/blob/414bd9d917dea2625a12eb3495350fe7003efc24/lib/github/pull-request.js#L8) which only looks for [pull_request.header and pull_request.head.ref](https://github.com/integrations/jira/blob/30e8a541196d09ca30d5ea680e579f692414eab2/lib/transforms/pull-request.js#L22).

So without digging too much more into it, it's possible that changing what the `transformPullRequest` method is parsing might fix this issue. So on [this line](https://github.com/integrations/jira/blob/30e8a541196d09ca30d5ea680e579f692414eab2/lib/transforms/pull-request.js#L22) changing the following _might_ just solve the issue.

```diff
-   const { issueKeys } = parseSmartCommit(`${pull_request.title}\n${pull_request.head.ref}`);
+   const { issueKeys } = parseSmartCommit(`${pull_request.title}\n${pull_request.head.ref}\n${pull_request.body}`);
```

**Comment by brwarner** [comment] 2021-05-07 00:22
I did some digging, and there was a PR with almost the exact change @pgrantmartello is suggesting but it was closed without merging for reasons I can't track down. You can find it here: https://github.com/integrations/jira/pull/121.

I did try giving development on this a go to submit my own PR but I was having a hard time getting the development environment working with the tunneling and everything.

**Comment by rachellerathbone** [comment] 2021-05-17 06:16
Hey @brwarner. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

I've flagged this with the 'to-triage' label so my team can discuss. We'll keep you posted on the status of this.

**Comment by cristianooliveira** [comment] 2021-06-18 14:17
> Hey @brwarner. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.
> 
> I've flagged this with the 'to-triage' label so my team can discuss. We'll keep you posted on the status of this.

Hi! @rachellerathbone do you have more news for us? https://github.com/integrations/jira/pull/448 seems to be stale. Would be awesome to have this feature 🙏

**Comment by rachellerathbone** [comment] 2021-08-11 03:32
Hey @cristianooliveira. Apologies for the slow response. 

We've been heads-down on the migration but are getting pretty close (only a few weeks out!). As soon as that's complete we'll be able to start working through our backlog of issues and look into this further.

**Comment by jfeldstein** [comment] 2021-10-14 02:53
Hey @rachellerathbone --

Thanks for your work flagging this. 

In the past few months, has the team gotten momentum? 

We could really use this bug fixed. Thank you!

**Comment by diogotorres97** [comment] 2022-01-10 10:03
Hi! @rachellerathbone  any updates on this?

**Comment by bgvozdev** [comment] 2022-01-10 21:52
Hey @diogotorres97 , we have just released this feature, could you please try now and see if it works for you or not?

**Comment by diogotorres97** [comment] 2022-01-11 08:30
@bgvozdev hmm, I don't think so. Do I need to do something extra to make it work?

**Comment by qnp** [comment] 2022-01-11 11:43
I confirm, it does not appear to be working as expected

**Comment by bgvozdev** [comment] 2022-01-11 20:58
@diogotorres97 @qnp A thousand apologies, I forgot to enable it in production but enabled in our staging environments. Could you please have a look once more? Just tested in prod myself, worked for me:
![image](https://user-images.githubusercontent.com/20631664/149020554-e322a89d-da54-4352-8ce5-f2580d15186b.png)

![image](https://user-images.githubusercontent.com/20631664/149020577-ad0797ea-93d2-43af-8642-5efb472e7e44.png)

**Comment by AlecRust** [comment] 2022-01-11 21:08
I'm not sure if this is covered already, but it's common to refer to multiple tickets within the description of a PR, but the PR itself only be associated with one Jira ticket.

I would only expect a PR to be linked to a Jira issue if it matched something like `fixes [TEST-12]` or `closes [TEST-12]`.

**Comment by diogotorres97** [comment] 2022-01-11 21:24
@bgvozdev it works!!!! Thanks a lot! 🚀 🎉

**Comment by bgvozdev** [comment] 2022-01-11 21:35
Hey @AlecRust , no, it is not covered here: all issue keys will be extracted and the associations will be built. I'd recommend you to open a separate issue/feature request for better tracking.

@diogotorres97 thanks for the confirmation!

I'm closing this issue, please feel to reopen or create a new one if you still have any questions.

**Closed by bgvozdev** 2022-01-11 21:35 UTC
Labels: awaiting response

**Comment by AlecRust** [comment] 2022-01-12 09:46
> I would only expect a PR to be linked to a Jira issue if it matched something like `fixes [TEST-12]` or `closes [TEST-12]`.

> I'd recommend you to open a separate issue/feature request for better tracking.

Sure, here it is: https://github.com/atlassian/github-for-jira/issues/1031

**Comment by qnp** [comment] 2022-01-12 10:26
@bgvozdev it works ! thanks
